<?php

namespace Okra\OkraBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OrdersItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdersItemRepository extends EntityRepository
{
    public function getStats()
    {
        return true;
    }
    
}
